// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Persistence;

#nullable disable

namespace Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260817205245_AllowMultipleSourcesPerMediaKind")]
    partial class AllowMultipleSourcesPerMediaKind
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Libraries.Library", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("kind")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Library");

                    b.HasDiscriminator<string>("kind").HasValue("Library");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Domain.Libraries.LibrarySource", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MediaKind")
                        .HasColumnType("integer");

                    b.Property<string>("kind")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.Property<Guid>("library_id")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("library_id", "MediaKind");

                    b.ToTable("LibrarySource");

                    b.HasDiscriminator<string>("kind").HasValue("LibrarySource");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Domain.Libraries.Physical.PhysicalLibrary", b =>
                {
                    b.HasBaseType("Domain.Libraries.Library");

                    b.HasDiscriminator().HasValue("physical");
                });

            modelBuilder.Entity("Domain.Libraries.Physical.PhysicalLibrarySource", b =>
                {
                    b.HasBaseType("Domain.Libraries.LibrarySource");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.HasIndex("Path")
                        .IsUnique();

                    b.HasDiscriminator().HasValue("physical");
                });

            modelBuilder.Entity("Domain.Libraries.Physical.PhysicalLibrarySource", b =>
                {
                    b.HasOne("Domain.Libraries.Physical.PhysicalLibrary", null)
                        .WithMany("Sources")
                        .HasForeignKey("library_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Libraries.Physical.PhysicalLibrary", b =>
                {
                    b.Navigation("Sources");
                });
#pragma warning restore 612, 618
        }
    }
}
