name: Add a new feature request
description: Create a detailed feature request
labels: [feature]

body:
- type: dropdown
  id: area
  attributes:
    label: Area
    description: What area does your feature belong to?
    options:
      - MovieLibrary
      - TvShowLibrary
      - Generic
  validations:
    required: true

- type: textarea
  attributes:
    label: Describe the feature
    description: A clear and concise description of what the feature is.
  validations:
    required: true