<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
      <PackageReference Include="FastEndpoints" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\..\Domain\Domain.csproj" />
      <ProjectReference Include="..\..\..\Persistence\Persistence.csproj" />
      <ProjectReference Include="..\..\Modules.Common\Modules.Common.csproj" />
      <ProjectReference Include="..\Libraries.Contracts\Libraries.Contracts.csproj" />
    </ItemGroup>

</Project>
