<Project Sdk="Aspire.AppHost.Sdk/13.2.2">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <UserSecretsId>ab4931ae-8899-4586-9819-ffeffda3f5cb</UserSecretsId>
        <AspireUseCliBundle>false</AspireUseCliBundle>
        <NoWarn>$(NoWarn);ASPIRE010</NoWarn>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Backend\Backend.csproj" />
      <ProjectReference Include="..\Frontend\Frontend.csproj" />
      <ProjectReference Include="..\ServiceDiscovery\ServiceDiscovery.csproj" IsAspireProjectResource="false" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Aspire.Hosting.AppHost" />
      <PackageReference Include="Aspire.Hosting.PostgreSQL" />
    </ItemGroup>

</Project>
