<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <PackageReference Include="FastEndpoints"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\..\Domain\Domain.csproj"/>
        <ProjectReference Include="..\..\Modules.Common\Modules.Common.csproj"/>
        <ProjectReference Include="..\Storage.Contracts\Storage.Contracts.csproj"/>
    </ItemGroup>
</Project>
