<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TestingPlatformDotnetTestSupport>true</TestingPlatformDotnetTestSupport>
    </PropertyGroup>

    <ItemGroup>
        <Using Include="Xunit"/>
    </ItemGroup>

    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="AwesomeAssertions"/>
        <PackageReference Include="xunit.v3.mtp-v2"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\..\..\src\modules\storage\Storage.Backend\Storage.Backend.csproj"/>
    </ItemGroup>

</Project>
